const axios = require("axios");
const TOKEN =
  "t1.9euelZqeyJuMjZSYypGMmZrGzM-Zju3rnpWalJeKjJKemZjGyJCezJuZj47l8_dhUBZ--e8PdHFq_d3z9yF_E3757w90cWr9.LVkN3NS2czrR3nJseTNRnq5qmYeJAoGgbL5asBesnk-14uiYVCE6Cl5Ah4DWAjiPgw4ie0VTynsVb7zr7WaQBQ";
const FOLDER_ID = "b1gieotoupq8010scg28"; // generated by `yc iam create-token`

module.exports = async (text, targetLanguageCode) => {
  try {
    const res = await axios.post(
      "https://translate.api.cloud.yandex.net/translate/v2/translate",
      {
        folder_id: FOLDER_ID,
        texts: text,
        targetLanguageCode: targetLanguageCode,
      },
      {
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${TOKEN}`,
        },
      }
    );
    return res;
  } catch (err) {
    console.error(err);
  }
};
