const express = require("express");
const fs = require("fs");
const axios = require("axios");
const TOKEN =
  "t1.9euelZqekYyVzImZyYqLmZ2Mi53Gyu3rnpWalJeKjJKemZjGyJCezJuZj47l8_d7bCx--e8XfTpT_t3z9zsbKn757xd9OlP-.bN9ekrp_M5nBWdXvTjBs_bOJBLfHL9MmcxwWao4pVdVufjVh_TEkeS09U6XF_2gGnB2P6BGWL4LhiAhRATOpBA";
const FOLDER_ID = "b1gieotoupq8010scg28"; // generated by `yc iam create-token`
const app = express();

app.use(express.static(__dirname + "/public"));
app.use(express.json());
app.use(express.urlencoded({ extended: true }));

app.get("/", (req, res) => {
  res.sendFile(__dirname + "/index.html");
});

app.post("/translate", async (req, res) => {
  let toTranslate = { ...req.body, FOLDER_ID };
  try{
    const response = await axios
      .post(
        "https://translate.api.cloud.yandex.net/translate/v2/translate",
        toTranslate,
        {
          headers: {
            "Content-Type": "application/json",
            Authorization: `Bearer ${TOKEN}`,
          },
        }
      )
    console.log(response.data)
  }catch(err){
    console.error(err)
  }
  res.end()
});

app.listen(3000, () => console.log("Listening on port 3000"));
