const axios = require("axios");
const TOKEN =
  "t1.9euelZqei8-bx42LnJSZmJyTj8qcku3rnpWalJeKjJKemZjGyJCezJuZj47l8_dVOCx--e93NEwa_t3z9xVnKX7573c0TBr-.8ELvJKJGu7bCL08zajDNqv1UlC2QSIKeZwRjt1tgCRPGpzXcwCgMlaibolMiZ14mLKCqwP_PgIXoobY_UEikAA";
const FOLDER_ID = "b1gieotoupq8010scg28"; // generated by `yc iam create-token`


const toTranslate = {
  folder_id: FOLDER_ID,
  texts: "Привет",
  targetLanguageCode: "it",
};

axios
  .post(
    "https://translate.api.cloud.yandex.net/translate/v2/translate",
    toTranslate,
    {
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${TOKEN}`,
      },
    }
  )
  .then((res) => console.log(res.data))
  .catch((err) => console.log(err));